import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './homeComponent.html',
  styleUrls: ['./homeComponent.css']
})
export class HomeComponent {

  menuOpen = false;

  toggleMenu() {
    this.menuOpen = !this.menuOpen;
  }

  hardware = [
    { icon: '', name: 'Square Register', desc: 'Your side runs the business. Their side checks out fast.', price: 'XAF899' },
    { icon: '', name: 'Square Handheld', desc: 'The POS that moves with you anywhere in your space.', price: 'XAF399' },
    { icon: '', name: 'Square Terminal', desc: 'The all-in-one credit card machine with receipt printing.', price: 'XAF299' },
    { icon: '', name: 'Square Stand', desc: 'The intuitive, swiveling iPad point of sale.', price: 'XAF149' },
    { icon: '', name: 'Square Reader', desc: 'The portable reader for every tap, dip, and swipe.', price: 'XAF59' },
  ];

  features = [
    { icon: '', title: 'Take payments', desc: 'Sell anything in person and online with a POS platform that works for whatever you sell.' },
    { icon: '', title: 'Manage your team', desc: 'Run payroll, schedule shifts, and take care of admin so your team can focus on performance.' },
    { icon: '', title: 'Grow your customer base', desc: 'Set up marketing campaigns and loyalty programs to welcome and keep customers.' },
    { icon: '', title: 'Control your cash flow', desc: 'Bring your revenue under one roof. Access funds instantly and get quicker access to loans.' },
    { icon: '', title: 'Sell online', desc: 'Build a free online store that syncs with your in-person inventory and payments automatically.' },
    { icon: '', title: 'Track inventory', desc: 'Know what you have, what you need, and what sells best — all from one dashboard.' },
  ];

  stats = [
    { industry: 'Food & Beverage', number: '450,000+', desc: 'food and beverage sellers using Square globally' },
    { industry: 'Retail', number: 'XAF39B+', desc: 'generated by retailers using Square annually' },
    { industry: 'Beauty', number: '15M+', desc: 'appointments booked through Square every month' },
    { industry: 'Services', number: 'XAF93B+', desc: 'paid with Square invoices globally' },
  ];

  testimonials = [
    { quote: 'Square has completely transformed how we run our café. Everything from payments to staff management is in one place.', name: 'Wazila Batinyuy ', business: 'Sunrise Café, Bamenda', initials: 'WB' },
    { quote: 'I used to spend hours doing my books. Now Square handles it automatically and I actually understand my numbers.', name: 'Loyce Ikem ', business: 'Fresh Cuts Barbershop', initials: 'LI' },
    { quote: 'The loyalty program brought back so many customers. Our repeat visit rate went up 40% in the first month.', name: 'Kumimyuy Fauzan', business: 'Glow Beauty Studio', initials: 'KF' },
  ];

  plans = [
    {
      name: 'Free', price: 'XAF0', period: 'per month, forever', featured: false, cta: 'Get started free',
      features: ['Point of sale', 'Free online store', 'Basic inventory', 'Standard reports', 'Free card reader', 'Email support']
    },
    {
      name: 'Plus', price: 'XAF29', period: 'per month, per location', featured: true, cta: 'Try free for 30 days',
      features: ['Everything in Free', 'Advanced reports', 'Lower processing rates', 'Loyalty programs', 'Marketing tools', 'Priority support']
    },
    {
      name: 'Premium', price: 'XAF99', period: 'contact sales for pricing', featured: false, cta: 'Contact sales',
      features: ['Everything in Plus', 'Dedicated account manager', 'Custom integrations', 'Volume discounts', 'SLA guarantees', '24/7 phone support']
    },
  ];

  footerCols = [
    { title: 'Products', links: ['Point of sale', 'Payments', 'Online store', 'Invoices', 'Marketing', 'Loyalty', 'Banking', 'Payroll', 'Hardware'] },
    { title: 'Business types', links: ['Restaurants', 'Retail', 'Beauty salon', 'Barbershop', 'Fitness', 'Professional services', 'Home & repair'] },
    { title: 'Resources', links: ['Pricing', 'Why Square', 'The Bottom Line', 'Support center', 'Community', 'Developer platform', 'Partner program'] },
    { title: 'Company', links: ['About', 'Press & media', 'Careers', 'Referrals', 'Investors', 'Security'] },
  ];
}
